# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='algolia_app_id',
            field=models.CharField(default='', help_text='Your Algolia.com App ID', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='algolia_public_key',
            field=models.CharField(default='', help_text='Your Algolia.com public key (NOT private key)', max_length=255),
            preserve_default=False,
        ),
    ]
