# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0002_auto_20171004_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='website_favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='algolia_app_id',
            field=models.CharField(default='', help_text='Your Algolia.com App ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='algolia_public_key',
            field=models.CharField(default='', help_text='Your Algolia.com public key (NOT private key)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Your Google Analytics ID. Example: UA-12345', max_length=255),
        ),
    ]
